[tool.poetry]
name = "fastapi-cruddy-framework"
version = "0.0.3"
description = "A holistic CRUD/MVC framework for FastAPI, with endpoint policies and relationships"
authors = ["mdconaway <mdconaway@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "fastapi_cruddy_framework"}]
homepage = "https://github.com/mdconaway/fastapi-cruddy-framework"
repository = "https://github.com/mdconaway/fastapi-cruddy-framework"
keywords = ["fastapi", "crud", "mvc", "orm", "ember", "sails", "json"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Framework :: FastAPI",
    "Operating System :: OS Independent",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
include = [
    "LICENSE",
]

[tool.black]
line-length = 88
target-version = ['py37']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/foo.py    # exclude a file named foo.py in the root of the project
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''

[tool.poetry.dependencies]
python = "^3.10"
fastapi = {extras = ["all"], version = "^0.92.0"}
uvicorn = "^0.20.0"
SQLAlchemy-Utils = "^0.38.3"
SQLAlchemy = "^1.4.40"
sqlmodel = "^0.0.8"
inflect = "^6.0.2"


[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
starlette-session = "^0.4.3"
aiosqlite = "^0.18.0"
greenlet = "^2.0.2"
bcrypt = "^4.0.1"

[tool.poetry.scripts]
start_sqlite = "examples.fastapi_cruddy_sqlite.main:local_start"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
