[tool.poetry]
name = "fastapi-cruddy-framework"
version = "1.7.2"
description = "A holistic CRUD/MVC framework for FastAPI, with endpoint policies and relationships"
authors = ["mdconaway <mdconaway@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "fastapi_cruddy_framework"}]
homepage = "https://github.com/mdconaway/fastapi-cruddy-framework"
repository = "https://github.com/mdconaway/fastapi-cruddy-framework"
keywords = ["fastapi", "crud", "mvc", "orm", "ember", "sails", "json"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Framework :: FastAPI",
    "Operating System :: OS Independent",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
include = [
    "LICENSE",
]

[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/foo.py    # exclude a file named foo.py in the root of the project
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
fastapi = {extras = ["all"], version = ">=0.100.0"}
SQLAlchemy-Utils = "^0.41.1"
SQLAlchemy = { extras = ["asyncio"], version = ">=2.0.0" }
sqlmodel = "^0.0.16"
inflect = "^7.0.0"
async-asgi-testclient = "^1.4.11"
validator-collection = "^1.5.0"
uuid7 = "^0.1.0"
redis = ">=5.0.1,<6.0.0"
fakeredis = ">=2.21.3"
async-timeout = ">=4.0.0,<5.0.0"
pymitter = ">=0.5.0"
strawberry-graphql = {extras = ["fastapi"], version = ">=0.223.0"}

[tool.poetry.group.dev.dependencies]
black = "^24.3.0"
uvicorn = "^0.24.0"
starlette-session = "^0.4.3"
aiosqlite = "^0.20.0"
bcrypt = "^4.1.2"
pylint = "^3.1.0"
pytest = "^8.1.1"
pytest-dependency = "^0.6.0"
coverage = "^7.4.4"

[tool.poetry.scripts]
start_sqlite = "examples.fastapi_cruddy_sqlite.bootloader:start"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[virtualenvs]
create = true
in-project = true
