[tool.poetry]
name = "fastapi-cruddy-framework"
version = "1.12.1"
description = "A holistic CRUD/MVC framework for FastAPI, with endpoint policies and relationships"
authors = ["mdconaway <mdconaway@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "fastapi_cruddy_framework"}]
homepage = "https://github.com/mdconaway/fastapi-cruddy-framework"
repository = "https://github.com/mdconaway/fastapi-cruddy-framework"
keywords = ["fastapi", "crud", "mvc", "orm", "ember", "sails", "json"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Framework :: FastAPI",
    "Operating System :: OS Independent",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
include = [
    "LICENSE",
]

[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/foo.py    # exclude a file named foo.py in the root of the project
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
fastapi = {extras = ["all"], version = ">=0.128.0"}
SQLAlchemy-Utils = "^0.42.1"
SQLAlchemy = { extras = ["asyncio"], version = ">=2.0.0" }
sqlmodel = "^0.0.31"
inflect = "^7.0.0"
async-asgi-testclient = "^1.4.11"
validator-collection = "^1.5.0"
uuid7 = "^0.1.0"
redis = ">=7.1.0"
fakeredis = ">=2.33.0"
async-timeout = ">=5.0.1"
pymitter = ">=1.1.3"
strawberry-graphql = {extras = ["fastapi"], version = ">=0.289.8"}
click = "^8.1.0"
pydantic-settings = ">=2.0.0"

[tool.poetry.group.dev.dependencies]
black = "^26.1.0"
uvicorn = "^0.40.0"
starlette-session = "^0.4.3"
aiosqlite = "^0.21.0"
bcrypt = "^5.0.0"
pylint = "^4.0.4"
pytest = "^9.0.2"
pytest-dependency = "^0.6.0"
coverage = "^7.13.2"

[tool.poetry.scripts]
start_sqlite = "examples.fastapi_cruddy_sqlite.bootloader:start"
cruddy = "fastapi_cruddy_framework.cli.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[virtualenvs]
create = true
in-project = true
